#!/bin/bash
# VNC xstartup script - starts desktop session inside VNC

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Set X11 session environment
export XDG_SESSION_TYPE=x11
export DESKTOP_SESSION=ubuntu
export XDG_CURRENT_DESKTOP=ubuntu:GNOME
export GNOME_SHELL_SESSION_MODE=ubuntu
export XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop

# Set grey background
xsetroot -solid grey
vncconfig -iconic &

# Start gnome-terminal (lightweight alternative to full GNOME shell)
gnome-terminal &
